name: younoter
description: YouTube Live Chat 專業管理工具
publish_to: 'none'
version: 1.0.3+1

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Database
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1

  # YouTube API
  googleapis: ^14.0.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  html: ^0.15.5

  # Routing
  go_router: ^14.8.1

  # UI
  fl_chart: ^0.70.2
  window_manager: ^0.4.3
  url_launcher: ^6.3.1

  # Utils
  uuid: ^4.5.1
  collection: ^1.19.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/


